ParanoidSense: Synchronization on dedicated lock objects instead of primitive ints
Fixes this build error:
FAILED: out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlin/ParanoidSense.jar out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlin_headers/ParanoidSense.jar
rm -rf "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/classes" "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/header_classes" "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/srcJars" "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc-build.xml" "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/empty" && mkdir -p "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/classes" "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/header_classes" "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/srcJars" "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/empty" && out/host/linux-x86/bin/zipsync -d out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/srcJars -l out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/srcJars/list -f "*.java" -f "*.kt"  && out/host/linux-x86/bin/gen-kotlin-build-file --classpath "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/classpath.rsp" --name "packages__apps__ParanoidSense__android_common__ParanoidSense" --out_dir "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/classes" --srcs "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlin/ParanoidSense.jar.rsp" --srcs "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/srcJars/list"  --out "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc-build.xml" && external/kotlinc/bin/kotlinc   -J--add-opens=java.base/java.util=ALL-UNNAMED -J-Xmx4096M  -Xsuppress-version-warnings -Xconsistent-data-class-copy-visibility -Xsam-conversions=class -no-stdlib -no-jdk -jvm-target 21 -Xbuild-file=out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc-build.xml  -kotlin-home out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/empty  -Xplugin=external/kotlinc/lib/jvm-abi-gen.jar  -P plugin:org.jetbrains.kotlin.jvm.abi:outputDir=out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/header_classes && out/host/linux-x86/bin/soong_zip -jar -o out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlin/ParanoidSense.jar -C out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/classes -D out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/classes -write_if_changed && out/host/linux-x86/bin/soong_zip -jar -o out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlin_headers/ParanoidSense.jar -C out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/header_classes -D out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/header_classes -write_if_changed && rm -rf "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/srcJars" "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/classes" "out/soong/.intermediates/packages/apps/ParanoidSense/ParanoidSense/android_common/kotlinc/header_classes"
packages/apps/ParanoidSense/src/co/aospa/sense/SenseService.kt:65:55: error: synchronizing by 'kotlin.Int' is forbidden
                ALARM_TIMEOUT_FREEZED -> synchronized(mLockoutType) {
                                                      ^^^^^^^^^^^^
packages/apps/ParanoidSense/src/co/aospa/sense/SenseService.kt:70:34: error: synchronizing by 'kotlin.Int' is forbidden
                    synchronized(mLockoutType) { mLockoutType = LOCKOUT_TYPE_DISABLED }
                                 ^^^^^^^^^^^^
packages/apps/ParanoidSense/src/co/aospa/sense/SenseService.kt:71:34: error: synchronizing by 'kotlin.Int' is forbidden
                    synchronized(mAuthenticationErrorCount) { mAuthenticationErrorCount = 0 }
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
packages/apps/ParanoidSense/src/co/aospa/sense/SenseService.kt:370:22: error: synchronizing by 'kotlin.Int' is forbidden
        synchronized(mAuthenticationErrorCount) {
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
packages/apps/ParanoidSense/src/co/aospa/sense/SenseService.kt:383:30: error: synchronizing by 'kotlin.Int' is forbidden
                synchronized(mLockoutType) {
                             ^^^^^^^^^^^^
packages/apps/ParanoidSense/src/co/aospa/sense/SenseService.kt:389:30: error: synchronizing by 'kotlin.Int' is forbidden
                synchronized(mLockoutType) {
                             ^^^^^^^^^^^^
packages/apps/ParanoidSense/src/co/aospa/sense/SenseService.kt:412:22: error: synchronizing by 'kotlin.Int' is forbidden
        synchronized(mAuthenticationErrorCount) {
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
00:38:58 ninja failed with: exit status 1
There was 1 action that completed after the action that failed. See verbose.log.gz for its output.

Change-Id: I55753f1c55ba95d113a09bfb10adbc831b2978a4